projeto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

recipes/urls.py
from django.urls import path
from . import views


app_name = 'recipes'

urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

recipes/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=166)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')

    # relação com a classe category
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)

recipes/views.py
from django.shortcuts import render
from utils.recipes.factory import make_recipe


def home(request):
    return render(request, 'recipes/pages/home.html', context={
        'recipes': [make_recipe() for _ in range(10)],
    })


def recipe(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': make_recipe(),
        'is_detail_page': True,
    })

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %} HOME | {% endblock title %}

        {% block content %}
        <div class="main-content main-content-list container">
            {% for recipe in recipes  %}
                 {% include 'recipes/partials/recipe.html' %}
            {% endfor %}
        </div>
        {% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %} Alterar | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
<div class="developer">
<a href="https://github.com/hoffmannvinicius" target="_blank" rel="noreferrer noopener">By Vinicius Hoffmann</a>
</div>

<div class="powered">
    <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
  </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/fontawesome.min.css"
        integrity="sha512-SgaqKKxJDQ/tAUAAXzvxZz33rmn7leYDYfBP+YoMRSENhf3zJyx3SBASt/OfeQwBHA1nxMis7mM3EV/oYT6Fdw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/brands.min.css"
        integrity="sha512-9YHSK59/rjvhtDcY/b+4rdnl0V4LPDWdkKceBl8ZLF5TB6745ml1AfluEU6dFWqwDw9lPvnauxFgpKvJqp7jiQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/solid.min.css"
        integrity="sha512-yDUXOUWwbHH4ggxueDnC5vJv4tmfySpVdIcN1LksGZi8W8EVZv4uKGrQc0pVf66zS7LDhFJM7Zdeow1sw1/8Jw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Archivo+Narrow:wght@700&family=Roboto+Condensed:wght@700&display=swap"
        rel="stylesheet">

        <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1> 
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fas fa-utensils main-logo-icon"></i>
                 <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
        <img src="{{recipe.cover.url}}" alt="Temporário">   
        </a>
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
            {{recipe.title}}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {{recipe.author.first_name}} {{recipe.author.last_name}}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:"d/m/Y"}} às {{recipe.created_at|date:"H:i"}}
        </span>
        <span class="recipe-author-item">
            <a href="/recipes/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>{{recipe.category.name}}</span>
            </a>
        </span>
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
    <div class="preparation-steps">
        {{ recipe.preparation_steps|linebreaksbr }}
    </div>
    {% endif %}

</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form class="search-form" action="">
            <input class="search-input" type="search" name="search">
            <button class="search-button" type="submit"> <i class="fas fa-search"></i> </button>
        </form>
    </div>
</div>